/* Données projets — partagées entre pages et transitions Barba */
window.PROJECTS = {
  'saline-ceviche': {
    slug: 'saline-ceviche',
    title: 'Saline Céviché',
    num: '01',
    year: '2024',
    type: 'Restaurant · Site Vitrine',
    accent: '#0B1A0E',
    video: '../assets/projects/saline-ceviche.mp4',
    poster: '../assets/projects/saline-ceviche.jpg',
    description:
      'Expérience digitale immersive pour un restaurant de cuisine marine à Biarritz. Navigation fluide, visuels plein écran et identité côtière forte.',
    role:
      'Direction artistique, développement front-end et intégration CMS — site vitrine performant, mobile-first, optimisé conversion.',
    website: 'https://www.salinebiarritz.com/',
    deliverables: [
      'Direction artistique & UI',
      'Intégration front-end sur mesure',
      'Animations & micro-interactions',
      'SEO technique & performance',
      'Mise en production & suivi',
    ],
    stack: ['HTML / CSS / JS', 'GSAP', 'CMS headless'],
    metricsLeft: [
      { label: 'PERF_SCORE', value: 95, suffix: '+' },
      { label: 'PAGES_BUILT', value: 8, prefix: '~' },
      { label: 'MICRO_ANIMS', value: 12, suffix: '+' },
    ],
    metricsRight: [
      { label: 'DELIVERY', value: 4, suffix: ' sem.' },
      { label: 'MODULES', value: 5 },
      { label: 'SEO_READY', value: 100, suffix: '%' },
    ],
    terminal: [
      '> Loading marine identity layer...',
      '> Mounting hero & menu modules...',
      '> Optimizing Core Web Vitals...',
      '> CMS sync · reservations online',
    ],
    prev: 'laetitia-nutrition',
    next: 'cap-nage',
  },
  'cap-nage': {
    slug: 'cap-nage',
    title: "Cap'Nage",
    num: '02',
    year: '2024',
    type: 'Sport & Bien-être · Web App',
    accent: '#0A1220',
    video: '../assets/projects/cap-nage.mp4',
    poster: '../assets/projects/cap-nage.jpg',
    description:
      'Plateforme de réservation pour une école de natation du littoral basque. Parcours simplifié, créneaux en temps réel et paiement sécurisé.',
    role:
      'Conception UX/UI, architecture front et intégration API pour une web app réactive et accessible.',
    website: 'https://www.cap-nage.fr/',
    deliverables: [
      'UX research & wireframes',
      'Design system & UI kit',
      'Application web responsive',
      'Intégration API réservation',
      'Tests & déploiement',
    ],
    stack: ['React', 'Node.js', 'PostgreSQL'],
    metricsLeft: [
      { label: 'API_ROUTES', value: 12 },
      { label: 'UI_SCREENS', value: 14 },
      { label: 'BOOKINGS', value: 500, suffix: '+' },
    ],
    metricsRight: [
      { label: 'DELIVERY', value: 8, suffix: ' sem.' },
      { label: 'TEST_COVERAGE', value: 80, suffix: '%' },
      { label: 'UPTIME', value: 99, suffix: '%' },
    ],
    terminal: [
      '> Initializing booking engine...',
      '> Connecting payment gateway...',
      '> Syncing slot availability...',
      '> Deploy · production ready',
    ],
    prev: 'saline-ceviche',
    next: 'simply-leads',
  },
  'simply-leads': {
    slug: 'simply-leads',
    title: 'SimplyLeads',
    num: '03',
    year: '2025',
    type: 'SaaS · Application Web',
    accent: '#160E1E',
    video: '../assets/projects/simply-leads.mp4',
    poster: '../assets/projects/simply-leads.jpg',
    description:
      'Outil de génération et gestion de leads pour PME et indépendants. Dashboard clair, automatisations et exports pour fluidifier la prospection.',
    role:
      'Design produit, développement full stack et parcours onboarding pour un SaaS B2B orienté conversion.',
    website: 'https://www.simplyleads.fr/',
    deliverables: [
      'Product design & prototypage',
      'Dashboard & flows utilisateur',
      'Back-end & authentification',
      'Intégrations CRM / email',
      'Monitoring & analytics',
    ],
    stack: ['Next.js', 'TypeScript', 'Prisma'],
    metricsLeft: [
      { label: 'DASHBOARD_VIEWS', value: 18 },
      { label: 'INTEGRATIONS', value: 8 },
      { label: 'API_ENDPOINTS', value: 24 },
    ],
    metricsRight: [
      { label: 'DELIVERY', value: 12, suffix: ' sem.' },
      { label: 'USERS_SCALE', value: 1000, prefix: '+' },
      { label: 'MODULES', value: 5 },
    ],
    terminal: [
      '> Booting SaaS environment...',
      '> Auth & roles configured',
      '> CRM webhooks connected',
      '> Analytics pipeline live',
    ],
    prev: 'cap-nage',
    next: 'jmmc-shop',
  },
  'jmmc-shop': {
    slug: 'jmmc-shop',
    title: 'JMMC Shop',
    num: '04',
    year: '2024',
    type: 'Mode · E-Commerce Shopify',
    accent: '#1A1006',
    video: '../assets/projects/jmmc-shop.mp4',
    poster: '../assets/projects/jmmc-shop.jpg',
    description:
      'Boutique en ligne haut de gamme pour une marque de mode locale. Mise en scène éditoriale des collections et parcours d\'achat premium.',
    role:
      'Thème Shopify custom, direction visuelle et optimisation du tunnel d\'achat pour une expérience e-commerce élégante.',
    website: 'https://www.jmmcshop.com/fr/',
    deliverables: [
      'Thème Shopify sur mesure',
      'Templates collection & produit',
      'Motion design storefront',
      'Setup paiement & livraison',
      'Formation & documentation',
    ],
    stack: ['Shopify', 'Liquid', 'JavaScript'],
    metricsLeft: [
      { label: 'PRODUCTS', value: 200, suffix: '+' },
      { label: 'TEMPLATES', value: 6 },
      { label: 'PERF_SCORE', value: 92, suffix: '+' },
    ],
    metricsRight: [
      { label: 'DELIVERY', value: 8, suffix: ' sem.' },
      { label: 'CONV_TARGET', value: 3, suffix: '%' },
      { label: 'UPTIME', value: 99, suffix: '%' },
    ],
    terminal: [
      '> Loading Shopify theme...',
      '> Product catalog synced',
      '> Checkout flow optimized',
      '> Storefront · live',
    ],
    prev: 'simply-leads',
    next: 'laetitia-nutrition',
  },
  'laetitia-nutrition': {
    slug: 'laetitia-nutrition',
    title: 'Laetitia Nutrition',
    num: '05',
    year: '2025',
    type: 'Nutrition · Site Vitrine',
    accent: '#0E1A0C',
    video: '../assets/projects/laetitia-nutrition.mp4',
    poster: '../assets/projects/laetitia-nutrition.jpg',
    description:
      'Site vitrine et blog pour une diététicienne indépendante. Ton rassurant, prise de rendez-vous en ligne et contenus éditoriaux SEO local.',
    role:
      'Identité digitale, site vitrine et blog avec focus SEO local, accessibilité et prises de contact.',
    deliverables: [
      'Branding digital & UI',
      'Site vitrine responsive',
      'Blog & catégories',
      'Formulaire contact / RDV',
      'SEO local & Core Web Vitals',
    ],
    stack: ['Astro', 'Tailwind', 'MDX'],
    metricsLeft: [
      { label: 'SEO_SCORE', value: 90, suffix: '+' },
      { label: 'BLOG_CATS', value: 12 },
      { label: 'PAGES', value: 10 },
    ],
    metricsRight: [
      { label: 'DELIVERY', value: 4, suffix: ' sem.' },
      { label: 'ACCESS', value: 100, suffix: '% AA' },
      { label: 'MODULES', value: 5 },
    ],
    terminal: [
      '> Deploying vitrine layout...',
      '> Blog MDX pipeline ready',
      '> Local SEO metadata set',
      '> Contact forms · online',
    ],
    prev: 'jmmc-shop',
    next: 'saline-ceviche',
  },
};

window.MF_PROJECT_ORDER = [
  'saline-ceviche',
  'cap-nage',
  'simply-leads',
  'jmmc-shop',
  'laetitia-nutrition',
];
